version: '3.8'

services:
  db:
    container_name: base-mariadb
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=techchallenge_root
      - MYSQL_DATABASE=techchallenge
      - MYSQL_USER=techchallenge
      - MYSQL_PASSWORD=techchallenge_pwd
    ports:
      - 3366:3306
  app:
    container_name: techchallenge-app
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/techchallenge?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=techchallenge
      - SPRING_DATASOURCE_PASSWORD=techchallenge_pwd
      - APP_JWT_SECRET=@cJ+OG!_GcYCz'_S(WP-wJ2#)i.nb4R!xMOeDMN-9)XTuwQ%Gk
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
