apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-mariadb
  labels:
    app: base-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-mariadb
  template:
    metadata:
      labels:
        app: base-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "techchallenge_root"
            - name: MYSQL_DATABASE
              value: "techchallenge"
            - name: MYSQL_USER
              value: "techchallenge"
            - name: MYSQL_PASSWORD
              value: "techchallenge_pwd"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
