INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('LANCHES', 'McCrispy Chicken Elite', 'Composto por pão tipo brioche com batata, molho Honey&Fire, bacon em fatias, alface, tomate, queijo sabor cheddar e carne 100% de peito de frango, temperada e empanada', 32.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('LANCHES', 'Brabo Bacon Salad', 'Composto pelo nosso pão tipo brioche, hambúrguer de carne 100% bovina, a nova Méquinese, exclusiva maionese especial com sabor de carne defumada, alface, tomate, fatias de bacon e queijo sabor cheddar', 37.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('LANCHES', 'Quarterão Com Queijo', 'Um hambúrguer (100% carne bovina), queijo cheddar, picles, cebola, ketchup, mostarda e pão com gergelim', 15.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('LANCHES', 'Cheddar McMelt', 'Um hambúrguer (100% carne bovina), molho cremoso sabor cheddar, cebola ao molho shoyu e pão escuro com gergelim', 18.50);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('LANCHES', 'Duplo Burger Com Queijo', 'Dois hambúrgueres, uma explosão de sabor. Dois deliciosos hambúrgueres de carne 100% bovina, queijo cheddar derretido, picles, cebola picada, ketchup e mostarda', 11.90);

INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('ACOMPANHAMENTOS', 'McFritas Grande', 'Deliciosas batatas selecionadas, fritas, crocantes por fora, macias por dentro, douradas, irresistíveis, saborosas, famosas, e todos os outros adjetivos positivos que você quiser dar', 14.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('ACOMPANHAMENTOS', 'McFritas Média', 'Deliciosas batatas selecionadas, fritas, crocantes por fora, macias por dentro, douradas, irresistíveis, saborosas, famosas, e todos os outros adjetivos positivos que você quiser dar', 12.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('ACOMPANHAMENTOS', 'McFritas Pequena', 'Deliciosas batatas selecionadas, fritas, crocantes por fora, macias por dentro, douradas, irresistíveis, saborosas, famosas, e todos os outros adjetivos positivos que você quiser dar', 10.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('ACOMPANHAMENTOS', 'McFritas Cheddar Bacon', 'As deliciosas batatas com molho cheddar e pedacinhos de bacon', 17.50);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('ACOMPANHAMENTOS', 'Molho CBO', 'O saboroso molho CBO, agora no tamanho ideal para você mergulhar suas méquizices', 6.90);

INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('BEBIDAS', 'Coca-Cola 500ml', 'Bebida gelada na medida certa para matar sua sede. Refrescante Coca-Cola 500ml', 14.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('BEBIDAS', 'Fanta Laranja 500ml', 'Bebida gelada na medida certa para matar sua sede. Refrescante Fanta sabor Laranja 500ml', 14.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('BEBIDAS', 'Fanta Guaraná 500ml', 'Bebida gelada na medida certa para matar sua sede. Refrescante Fanta Guaraná 500ml', 14.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('BEBIDAS', 'McShake Morango 400ml', 'O novo McShake é feito com leite e batido na hora com calda de morango', 16.90);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('BEBIDAS', 'McShake Chocolate 400ml', 'O novo McShake é feito com leite e batido na hora com o delicioso chocolate Kopenhagen', 16.90);

INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('SOBREMESAS', 'Top Sundae - Calda de Chocolate', 'Bebida láctea sabor baunilha com uma super camada de cobertura de chocolate e ainda por cima com farofa de paçoca. O canudo completa a tentação', 11.00);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('SOBREMESAS', 'Top Sundae Calda de Morango', 'Bebida láctea sabor baunilha com uma super camada de cobertura de morango e ainda por cima com farofa de paçoca. O canudo completa a tentação', 11.00);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('SOBREMESAS', 'McColosso Chocolate', 'Não é uma sobremesa qualquer, é um verdadeiro colosso. Uma supercasquinha de biscoito em forma de cone, recheada com massa gelada de baunilha e uma sensacional cobertura de chocolate. E, além de todo esse sabor, um canudinho de biscoito supercrocante', 6.00);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('SOBREMESAS', 'Torta de Banana', 'Deliciosa torta de massa quentinha e crocante com recheio de banana. Não utilize o campo de observações, as alterações devem ser realizadas no pedido', 7.50);
INSERT INTO produtos (categoria, nome, descricao, preco) VALUES ('SOBREMESAS', 'Torta de Maçã', 'Deliciosa torta de massa quentinha e crocante com recheio de maçã. Não utilize o campo de observações, as alterações devem ser realizadas no pedido', 7.50);